apiVersion: v1
kind: Service
metadata:
  name: swiggy-app
  labels:
    app: swiggy-app
spec:
  #type: LoadBalancer
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: swiggy-app
